/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_asav_processimage_GAPITester */

#ifndef _Included_com_asav_processimage_GAPITester
#define _Included_com_asav_processimage_GAPITester
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_asav_processimage_GAPITester
 * Method:    gapiInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_asav_processimage_GAPITester_gapiInit
  (JNIEnv *, jclass);

/*
 * Class:     com_asav_processimage_GAPITester
 * Method:    gapiTest
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_asav_processimage_GAPITester_gapiTest
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
