/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_asav_processimage_MainActivity */

#ifndef _Included_com_asav_processimage_MainActivity
#define _Included_com_asav_processimage_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_asav_processimage_MainActivity_SELECT_PICTURE
#define com_asav_processimage_MainActivity_SELECT_PICTURE 1L
/*
 * Class:     com_asav_processimage_MainActivity
 * Method:    niBlackThreshold
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_asav_processimage_MainActivity_niBlackThreshold
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
